# Generated by Django 3.2.9 on 2021-12-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
